apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: kustomize-prod

patches:
- path: deployment-patch.yaml
- path: service-patch.yaml

namePrefix: staging-

replicas:
- count: 1
  name: gitops-demo

configMapGenerator:
- literals:
  - Database=staging
  name: database-config

images:
- name: ashrafelshazlii/gitops-demo
  newTag: 0.1.0
