apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
spec:
  selector:
    matchLabels:
      app: gitops-demo
  template:
    spec:
      containers:
        - name: gitops-demo
          ports:
            - containerPort: 8082