apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: kustomize-prod

patches:
- path: deployment-patch.yaml
- path: service-patch.yaml

namePrefix: prod-

replicas:
- count: 2
  name: gitops-demo

configMapGenerator:
- literals:
  - Database=prod
  name: database-config

images:
- name: ashrafelshazlii/java-app-test
  newTag: 1.1.1
